Start testing: Aug 30 21:17 CEST
----------------------------------------------------------
1/1 Testing: qa_corr_dist_estimator_bfi
1/1 Test: qa_corr_dist_estimator_bfi
Command: "/usr/bin/sh" "/home/jonas/Documents/university/SDR-Positioning-System/gnuradio/CodeRadar/gr-lab_radar/build/python/qa_corr_dist_estimator_bfi_test.sh"
Directory: /home/jonas/Documents/university/SDR-Positioning-System/gnuradio/CodeRadar/gr-lab_radar/build/python
"qa_corr_dist_estimator_bfi" start time: Aug 30 21:17 CEST
Output:
----------------------------------------------------------
.E
======================================================================
ERROR: test_002_t (__main__.qa_corr_dist_estimator_bfi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/Documents/university/SDR-Positioning-System/gnuradio/CodeRadar/gr-lab_radar/python/qa_corr_dist_estimator_bfi.py", line 112, in test_002_t
    with open(src_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/university/SDR-Positioning-System/gnuradio/CodeRadar/gr-lab_radar/python/source.txt'

----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (errors=1)
<end of output>
Test time =   0.70 sec
----------------------------------------------------------
Test Failed.
"qa_corr_dist_estimator_bfi" end time: Aug 30 21:17 CEST
"qa_corr_dist_estimator_bfi" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Aug 30 21:17 CEST
